# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ArmTemplatePipeline'
    subscriptionId: 'e2ad7149-754e-4628-a8dc-54a49b116708'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'arm-pipeline-rg'
    location: 'Canada Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/yusbel/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName armtemp'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
